# Generated by Django 5.2.16 on 2026-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('license', models.CharField(blank=True, max_length=64)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('safety_score', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
