# Generated by Django 5.2.16 on 2026-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=16),
        ),
    ]
